#!/usr/bin/env python

from os import system
import curses

def get_param(prompt_string):
	screen.clear()
	screen.border(0)
	screen.addstr(2, 2, prompt_string)
	screen.refresh()
	input = screen.getstr(10, 10, 60)
	return input

def execute_cmd(cmd_string):
	system("clear")
	a = system(cmd_string)
	print ""
	if a == 0:
		print "Command executed correctly"
	else:
		print "Command terminated with error"
	raw_input("Press enter")
	print ""

x = 0

while x != ord('5'):
	screen = curses.initscr()

	screen.clear()
	screen.border(0)
	screen.addstr(2, 2, "Please enter a number...")
	screen.addstr(4, 4, "1 - Clear")
	screen.addstr(5, 4, "2 - Show list")
	screen.addstr(6, 4, "3 - Make a dir")
	screen.addstr(7, 4, "4 - Remove a dir")
	screen.addstr(8, 4, "5 - Exit")
	screen.refresh()

	x = screen.getch()

	if x == ord('1'):			
		curses.endwin()
		execute_cmd("clear")
	if x == ord('2'):
		curses.endwin()
		execute_cmd("ls")
	if x == ord('3'):
		nameofdir = get_param("Enter the name of dir")
		curses.endwin()
		execute_cmd("mkdir " + nameofdir)
	if x == ord('4'):
		nameofdir = get_param("Enter the name of dir")
		curses.endwin()
		execute_cmd("rmdir " + nameofdir)
curses.endwin()

